project:
  type: website
  output-dir: docs
  
website:
  page-navigation: false
  title: "Palaeobiology with R: Methods for deep-time data analysis"
  description: "Transmitting Science 2024 Course - Palaeobiology with R: Methods for deep-time data analysis"
  site-url: https://course.palaeobiology.org
  repo-url: https://github.com/LewisAJones/2024-TS-palaeobiology-with-r/
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  favicon: images/logo.png
  image: images/logo.png

  sidebar:
    border: true
    logo: images/logo.png
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/LewisAJones
        text: "GitHub"
      - icon: twitter
        href: https://twitter.com/LewisAlanJones
        text: "Twitter"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: schedule.qmd
        text: Schedule
      - href: instructors.qmd
        text: Instructors
      - section: "Day 1"
        contents:
          - href: Day_01/unit_01.qmd
            text: Unit 1
          - href: Day_01/unit_02.qmd
            text: Unit 2
      - section: "Day 2"
        contents:
          - href: Day_02/unit_03.qmd
            text: Unit 3
          - href: Day_02/unit_04.qmd
            text: Unit 4
      - section: "Day 3"
        contents:
          - href: Day_03/unit_05.qmd
            text: Unit 5
          - href: Day_03/unit_06.qmd
            text: Unit 6
      - section: "Day 4"
        contents:
          - href: Day_04/unit_07.qmd
            text: Unit 7
          - href: Day_04/unit_08.qmd
            text: Unit 8
      - section: "Day 5"
        contents:
          - href: Day_05/unit_09.qmd
            text: Unit 9
          - href: Day_05/unit_10.qmd
            text: Unit 10
            
  page-footer:
    border: true
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Lewis A. Jones"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

editor: source