---
title: "Palaeobiology with R: Methods for deep-time data analysis"
---

# Course overview

In this introductory course to Analytical Palaeobiology attendees will be provided with an extensive guide to the theory behind it, and tools available for getting started with reconstructing deep-time macroecological and macroevolutionary patterns.

First, key concepts such as the structure of the fossil record and associated geological and anthropogenic biases will be introduced, followed by the type of data and databases available for reconstructing deep-time biodiversity trends. Subsequently, we will introduce various tools available within the R environment for modelling deep-time macroecological and macroevolutionary patterns, and testing hypotheses.

This course will provide an extensive introduction to palaeoverse, an R package that supports data preparation and exploration for paleobiological analysis. Additional packages developed by Palaeoverse, such as rmacrostrat, will also be introduced along with the versatility R has to offer.

Participants are encouraged to bring their dataset (but not required), as the [schedule](schedule.qmd) will include time for applying the tools presented in the workshop to their research questions.

# Installation

Please ensure that you have the latest version of R installed for the course, which can be downloaded [here](https://cran.r-project.org). We also recommend installing the latest version of RStudio, which can be downloaded [here](https://posit.co/download/rstudio-desktop/). To minimize any installation issues during the workshop, please also install the following R packages:

```{r echo=TRUE, eval=FALSE}
install.packages(pkgs = c("palaeoverse", "rmacrostrat"))
```

# Intended audience and assumed background

This course is addressed to any palaeobiologist interested in learning tools to develop their analysis.

Basic knowledge of R is required to follow the course.

# Dates and schedule

Online live sessions on November 25–29^th^, 2024.

14:00--18:00 (Madrid time zone). See full [schedule](schedule.qmd).

Total course hours: 20.

# Format

In the live sessions, we will combine online lectures with hands-on computational exercises, in R. Participants are encouraged to bring their dataset (but not required), as the schedule will include time for applying the tools presented in the course to their research questions.

Live sessions will be recorded. However, attendance to the live sessions is required to obtain the course certificate.